### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ekholme** [ekholme/flex_creek#1]
- [x] Make User type
- [x] CRUD operations for Wod service
- [x] CRUD operations for User service
- [x] Wod handlers
- [ ] User handlers
- [x] Auth/jwt
- [ ] Favorite workouts
- [ ] Form validation
- [ ] Make HTML templates
